auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: raining.com
url: http://raining0822.github.io
feed: /atom.xml
author_info: <a href="http://raining0822.github.io">许洋</a>
